config/routes.rb
Rails.application.routes.draw do
  resources :celldbs
  get 'welcome/index'
  
  root 'welcome#index'  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/celldb.rb
class Celldb < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/celldbs_controller.rb
class CelldbsController < ApplicationController
  before_action :set_celldb, only: %i[ show edit update destroy ]

  # GET /celldbs or /celldbs.json
  def index
    @celldbs = Celldb.all
  end

  # GET /celldbs/1 or /celldbs/1.json
  def show
  end

  # GET /celldbs/new
  def new
    @celldb = Celldb.new
  end

  # GET /celldbs/1/edit
  def edit
  end

  # POST /celldbs or /celldbs.json
  def create
    @celldb = Celldb.new(celldb_params)

    respond_to do |format|
      if @celldb.save
        format.html { redirect_to @celldb, notice: "Celldb was successfully created." }
        format.json { render :show, status: :created, location: @celldb }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @celldb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /celldbs/1 or /celldbs/1.json
  def update
    respond_to do |format|
      if @celldb.update(celldb_params)
        format.html { redirect_to @celldb, notice: "Celldb was successfully updated." }
        format.json { render :show, status: :ok, location: @celldb }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @celldb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celldbs/1 or /celldbs/1.json
  def destroy
    @celldb.destroy
    respond_to do |format|
      format.html { redirect_to celldbs_url, notice: "Celldb was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_celldb
      @celldb = Celldb.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def celldb_params
      params.require(:celldb).permit(:cellnumber)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/celldbs_helper.rb
module CelldbsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/celldbs/_form.html.erb
<%= form_with(model: celldb) do |form| %>
  <% if celldb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(celldb.errors.count, "error") %> prohibited this celldb from being saved:</h2>

      <ul>
        <% celldb.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cellnumber %>
    <%= form.text_field :cellnumber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/celldbs/edit.html.erb
<h1>Editing Celldb</h1>

<%= render 'form', celldb: @celldb %>

<%= link_to 'Show', @celldb %> |
<%= link_to 'Back', celldbs_path %>

app/views/celldbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Celldbs</h1>

<table>
  <thead>
    <tr>
      <th>Cellnumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @celldbs.each do |celldb| %>
      <tr>
        <td><%= celldb.cellnumber %></td>
        <td><%= link_to 'Show', celldb %></td>
        <td><%= link_to 'Edit', edit_celldb_path(celldb) %></td>
        <td><%= link_to 'Destroy', celldb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Celldb', new_celldb_path %>

app/views/celldbs/new.html.erb
<h1>New Celldb</h1>

<%= render 'form', celldb: @celldb %>

<%= link_to 'Back', celldbs_path %>

app/views/celldbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cellnumber:</strong>
  <%= @celldb.cellnumber %>
</p>

<%= link_to 'Edit', edit_celldb_path(@celldb) %> |
<%= link_to 'Back', celldbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elpplz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>

<body> 




  <%= link_to 'index', welcome_index_path %>
  <%= link_to 'celldb', celldbs_path %>

 <script type="text/javascript">
  $(document).load(function(){
    testea();
  });
</script>


</body>
</html>